
file:
  upload-dir: /Users/zahir/Documents/dev/ds_flow/data
server:
  port: 9090
logging:
  level:
    org.springframework.web: DEBUG
spring:
  datasource:
    url: jdbc:mariadb://35.181.155.182:3306/indusml_db
    username: centos
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        hbm2ddl:
          auto: update
        id:
          new_generator_mappings: false